// GB GAMER BROS™ — area gallery data (Pass B)
// One entry per map location. The gallery is built entirely from this data plus
// media-manifest.js (generated by tools/gbmedia.py), which holds each image's content size
// and copyright-band size. Replacing an image = rebuild it with gbmedia.py under the same
// path (or a new path here). No gallery code or layout changes are needed, even if the new
// image has different proportions.
//
// status   open | incomplete | artwork-required   (only "open" areas can be entered)
// views[].kind     establishing | ground | traversal | landmark | closeup
// views[].label    working label (not final marketing copy)
// views[].focus    0–1 horizontal focal point for the portrait immersive crop
// views[].hotspots Pass E: boxes in % of the CONTENT image (the copyright band is excluded).
//                  `ref` is a canonical ID from entities.js, so a Goom here opens the same
//                  #entity/goom dossier as the Bad Guys & Hazards section:
//                  { ref:"goom", x:61, y:42, w:6, h:9 }   (optional `label` overrides the name)
//
// `map:false` entries are galleries that are not map locations (e.g. the Level Preview stills).

(() => {
const A = "assets/areas/";

window.GB_AREAS = {
  portal: {
    name: "Portal Meadow™", sub: "The Adventure Begins", status: "open",
    views: [
      { src: A + "portal-meadow/01-crystal_valley_portal_adventure", kind: "establishing", label: "Meadow portal", focus: 0.32,
        alt: "Grassy meadow with a glowing portal gate, fenced paths and terraced waterfalls", hotspots: [] },
      { src: A + "portal-meadow/02-adventure_mountain_portal_valley", kind: "ground", label: "Portal path", focus: 0.34,
        alt: "Ground-level dirt path through flowers leading to a stone portal arch", hotspots: [] },
      { src: A + "portal-meadow/03-gb_portal_overlooking_crystal_valley", kind: "closeup", label: "Cliffside portal", focus: 0.72,
        alt: "Cliffside stone path to a portal with a springboard, gems and crates", hotspots: [] },
    ],
  },
  creek: {
    name: "Creek Crossing™", sub: "Bridges & Rapids", status: "incomplete",
    // one reliable image so far; opens once more views exist
    views: [
      { src: A + "creek-crossing/01-enchanted_waterfall_canyon_adventure", kind: "traversal", label: "Plank bridge", focus: 0.5,
        alt: "Wooden plank bridge crossing over rapids between waterfalls", hotspots: [] },
    ],
  },
  river: {
    name: "Riverworks™", sub: "Waterfalls & Pipeways", status: "open",
    views: [
      { src: A + "riverworks/01-canyon_of_crystal_waterworks", kind: "establishing", label: "Pipeway canyon", focus: 0.48,
        alt: "Riverworks™ canyon from above: blue pipeways, stone bridges and waterfalls beside a glowing portal", hotspots: [] },
      { src: A + "riverworks/02-gb_waterfall_riverworks_adventure", kind: "ground", label: "Boardwalk", focus: 0.36,
        alt: "Player-height view along a wet boardwalk past a pipe waterfall, crates and a springboard", hotspots: [] },
      { src: A + "riverworks/03-riverworks_canyon_pipeline_adventure", kind: "traversal", label: "Pipeline route", focus: 0.66,
        alt: "Boardwalk route between large blue pipes with a springboard, gems and a signpost ahead", hotspots: [] },
      { src: A + "riverworks/04-cinematic_gb_mountain_waterfall_adventure", kind: "landmark", label: "Pipe falls", focus: 0.7,
        alt: "Cliffside walkway beside a pipe outflow waterfall, overlooking the terraced canyon", hotspots: [] },
    ],
  },
  clover: { name: "Clover Cliffs™", sub: "Forest Trails", status: "artwork-required", views: [] },
  ruin: {
    name: "Ruin Courtyard™", sub: "Forgotten Towers", status: "open",
    views: [
      { src: A + "ruin-courtyard/01-floating_ruins_portal_adventure", kind: "establishing", label: "Ruined terraces", focus: 0.66,
        alt: "Terraces of ruined stone arches and towers around a glowing portal", hotspots: [] },
      { src: A + "ruin-courtyard/02-vibrant_ruined_courtyard_adventure", kind: "ground", label: "Courtyard", focus: 0.48,
        alt: "Ground-level paved courtyard with broken arches, a signpost, an enemy and a portal gate", hotspots: [] },
      { src: A + "ruin-courtyard/03-mossy_gb_fortress_valley_adventure", kind: "traversal", label: "Fortress stairs", focus: 0.6,
        alt: "Stone path and stairs climbing through a mossy ruined fortress arch", hotspots: [] },
      { src: A + "ruin-courtyard/04-mountain_fortress_portal_ruins", kind: "landmark", label: "Tower portal", focus: 0.62,
        alt: "Ruined towers and stairs with a portal high on the ridge", hotspots: [] },
    ],
  },
  prism: {
    name: "Prism Ridge™", sub: "Crystal Peaks & Ancient Ruins", status: "open",
    views: [
      { src: A + "prism-ridge/01-adventure_mountain_prism_valley", kind: "establishing", label: "Crystal valley", focus: 0.62,
        alt: "Aerial view of the crystal citadel above terraced ruins, pipes and portals", hotspots: [] },
      { src: A + "prism-ridge/02-prism_ridge_valley_adventure", kind: "ground", label: "Ridge trail", focus: 0.42,
        alt: "Trail with a signpost toward Prism Ridge, overlooking the waterfall valley", hotspots: [] },
      { src: A + "prism-ridge/03-crystalline_mountain_citadel_adventure", kind: "traversal", label: "Crystal path", focus: 0.5,
        alt: "Crystal-lined stone path leading toward the crystal citadel", hotspots: [] },
      { src: A + "prism-ridge/04-a4", kind: "landmark", label: "Citadel stairs", focus: 0.76,
        alt: "Stone stairs climbing toward the crystal castle with gems and crates", hotspots: [] },
    ],
  },
  frost: { name: "Frost Peaks™", sub: "Icy Cliffs & Granite Roads", status: "artwork-required", views: [] },

  // Level Preview still sequence (not a map location). Opens in the same gallery view.
  preview: {
    name: "Level Preview", sub: "Preview stills · gameplay video not yet available", status: "open", map: false,
    views: [
      { src: "assets/systems/preview-01-boardwalk-run", kind: "still", label: "Boardwalk run", focus: 0.45,
        alt: "Gamer Bro Blue™ running along a boardwalk past waterfalls and gems", hotspots: [] },
      { src: "assets/systems/preview-02-ruin-stairs", kind: "still", label: "Ruin stairs", focus: 0.5,
        alt: "Gamer Bro Blue™ climbing stone stairs between waterfalls and ruins", hotspots: [] },
      { src: "assets/systems/preview-03-waterfall-ruins", kind: "still", label: "Waterfall ruins", focus: 0.55,
        alt: "Ruined aqueduct arches and waterfalls pouring into a clear pool", hotspots: [] },
      { src: "assets/systems/preview-04-trail-junction", kind: "still", label: "Trail junction", focus: 0.3,
        alt: "Stone steps at a trail junction with signposts, pipes and a waterfall", hotspots: [] },
    ],
  },
};
})();
