// GB GAMER BROS™ — area gallery data (Pass B)
// One entry per map location. The gallery is built entirely from this data plus
// media-manifest.js (generated by tools/gbmedia.py), which holds each image's content size
// and copyright-band size. Replacing an image = rebuild it with gbmedia.py under the same
// path (or a new path here). No gallery code or layout changes are needed, even if the new
// image has different proportions.
//
// status   open | incomplete | artwork-required   (only "open" areas can be entered)
// views[].kind     establishing | ground | traversal | landmark | closeup
// views[].label    working label (not final marketing copy)
// views[].focus    0–1 horizontal focal point for the portrait immersive crop
// views[].hotspots Pass E: boxes in % of the CONTENT image (the copyright band is excluded).
//                  `ref` is a canonical ID from entities.js, so a Goom here opens the same
//                  #entity/goom dossier as the Enemies & Hazards section:
//                  { ref:"goom", x:61, y:42, w:6, h:9 }   (optional `label` overrides the name)
//
// identity       region placeholder (theme + icon) shown on cards until real imagery exists
// `map:false` entries are galleries that are not map locations (e.g. the Level Preview stills).

(() => {
const A = "assets/areas/";

window.GB_AREAS = {
  portal: {
    name: "Portal Meadow™", sub: "The Adventure Begins", status: "open",
    views: [
      { src: A + "portal-meadow/pm01-broad-entry-path", kind: "establishing", label: "Entry path", focus: 0.45,
        alt: "Broad dirt path through wildflowers past a stone bridge and turquoise pool, with ruined towers on the cliffs beyond", hotspots: [] },
      { src: A + "portal-meadow/pm02-open-meadow-routes", kind: "ground", label: "Branching routes", focus: 0.58,
        alt: "Open meadow where the stone path branches toward broad stairs and a ruined arch", hotspots: [] },
      { src: A + "portal-meadow/pm03-first-ascent-cave-edge", kind: "traversal", label: "First ascent", focus: 0.55,
        alt: "Gentle path climbing past a stone bridge toward a lantern-lit cave entrance", hotspots: [] },
    ],
  },
  creek: {
    name: "Creek Crossing™", sub: "Bridges & Rapids", status: "open",
    views: [
      { src: A + "creek-crossing/cc01-low-water-crossing", kind: "establishing", label: "Low-water crossing", focus: 0.4,
        alt: "Lantern-lit stone steps and a masonry arch bridge over a turquoise creek", hotspots: [] },
      { src: A + "creek-crossing/cc02-branching-path", kind: "traversal", label: "Branching path", focus: 0.36,
        alt: "Stone stairs branching from the creek path beside a wooden rail", hotspots: [] },
      { src: A + "creek-crossing/cc03-creek-bank-bridge", kind: "landmark", label: "Under the bridge", focus: 0.55,
        alt: "Creek bank path running beneath a mossy masonry bridge", hotspots: [] },
    ],
  },
  river: {
    name: "Riverworks™", sub: "Waterfalls & Pipeways", status: "open",
    views: [
      { src: A + "riverworks/rw02-cliffside-waterworks", kind: "establishing", label: "Cliffside waterworks", focus: 0.62,
        alt: "Timber waterworks and blue pipes on the cliffside above a turquoise river and stone bridges", hotspots: [] },
      { src: A + "riverworks/rw03-maintenance-walkway", kind: "ground", label: "Maintenance walkway", focus: 0.68,
        alt: "Wood-and-stone maintenance walkway beside a large blue pipe and a stone pump house", hotspots: [] },
      { src: A + "riverworks/rw04-aqueduct-corridor", kind: "landmark", label: "Aqueduct corridor", focus: 0.5,
        alt: "Arched stone aqueduct corridor with blue pipes and channels of running water", hotspots: [] },
    ],
  },
  clover: {
    name: "Clover Cliffs™", sub: "Forest Trails", status: "open",
    views: [
      { src: A + "clover-cliffs/cl01-cliff-path-ruins", kind: "establishing", label: "Cliff path", focus: 0.62,
        alt: "Cliff path with wooden rails climbing stone stairs to ruined arches among pine trees", hotspots: [] },
      { src: A + "clover-cliffs/cl02-switchback-forest-route", kind: "traversal", label: "Switchback route", focus: 0.38,
        alt: "Stone stairs and a switchback trail winding down a forested cliff", hotspots: [] },
      { src: A + "clover-cliffs/cl03-cave-shelf-upper-path", kind: "ground", label: "Cave shelf", focus: 0.72,
        alt: "Grassy shelf path along the cliff toward a lantern-lit cave", hotspots: [] },
      { src: A + "clover-cliffs/cl04-cave-interior-channel", kind: "landmark", label: "Cave passage", focus: 0.62,
        alt: "Timber-braced cave passage with lanterns opening onto the forest cliffs", hotspots: [] },
    ],
  },
  ruin: {
    name: "Fallen Grounds™", sub: "Broken Arches & Old Stone", status: "open",
    views: [
      { src: A + "ruin-courtyard/rc01-broad-dry-courtyard", kind: "establishing", label: "Fallen Grounds", focus: 0.55,
        alt: "Broad paved courtyard between ivy-covered stone arches and ruined towers", hotspots: [] },
      { src: A + "ruin-courtyard/rc02-court-stairs-exits", kind: "ground", label: "Court stairs", focus: 0.5,
        alt: "Flat stone court with a great broken arch, broad stairs and archway exits", hotspots: [] },
      { src: A + "ruin-courtyard/rc03-layered-ruins-routes", kind: "traversal", label: "Layered ruins", focus: 0.62,
        alt: "Layered ruins with stairs and arched walkways leading to several routes", hotspots: [] },
    ],
  },
  prism: {
    name: "Prism Ridge™", sub: "Crystal Peaks & Ancient Ruins", status: "open",
    views: [
      { src: A + "prism-ridge/pr02-crystal-flatland", kind: "establishing", label: "Crystal flatland", focus: 0.55,
        alt: "Paved ruin plateau with violet crystals and the crystal citadel on the peaks beyond", hotspots: [] },
      { src: A + "prism-ridge/pr03-high-ridge-approach", kind: "traversal", label: "High ridge approach", focus: 0.6,
        alt: "Ridge path past ruined arches with a sightline to the crystal citadel", hotspots: [] },
      { src: A + "prism-ridge/pr04-prism-ruin-landing", kind: "ground", label: "Ruin landing", focus: 0.55,
        alt: "Broad stone landing among ruined towers and crystal clusters", hotspots: [] },
      { src: A + "prism-ridge/ss01-summit-portal-stairs", kind: "landmark", label: "Summit portal stairs", focus: 0.5,
        alt: "Grand staircase climbing between crystals and waterfalls to the summit portal", hotspots: [] },
    ],
  },
  frost: {
    name: "Frosty Peaks™", sub: "Icy Cliffs & Granite Roads", status: "open",
    views: [
      { src: A + "frost-peaks/fp01-snowy-plateau-icefalls", kind: "establishing", label: "Snowy plateau", focus: 0.5,
        alt: "Snowy plateau with a rope bridge over frozen icefalls and a ruined tower on the peak", hotspots: [] },
      { src: A + "frost-peaks/fp02-rope-bridge-snowy-shelf", kind: "traversal", label: "Rope bridge", focus: 0.52,
        alt: "Lantern-lit rope bridge crossing to a snowy stone shelf below the summit", hotspots: [] },
      { src: A + "frost-peaks/fp04-frost-to-summit-spine", kind: "landmark", label: "Toward Summit Spine™", focus: 0.42,
        alt: "Snowy path from Frosty Peaks™ toward the crystal summit and its glowing portal", hotspots: [] },
    ],
  },
  // Level Preview still sequence (not a map location). Opens in the same gallery view.
  preview: {
    name: "Level Preview", sub: "Preview stills", status: "open", map: false,
    views: [
      // Owner canon audit 2026-10-10 (issue #1): the three character action stills formerly here
      // (blue-red-world-action-01, purple-yellow-world-action-02, four-character-world-action-01)
      // show floating islands, contrary to ONE CONNECTED MOUNTAIN. Removed pending owner-approved scenes.
      { src: "assets/systems/preview-04-trail-junction", kind: "still", label: "Trail junction", focus: 0.3,
        alt: "Stone steps at a trail junction with signposts, pipes and a waterfall", hotspots: [] },
    ],
  },
};
})();
