#!/usr/bin/env python3
"""GB GAMER BROS™ — Adventure Mountain™ 360° panorama builder.

Turns the private panorama master into the public world-viewer derivatives and writes
panorama-manifest.js. The master itself is never copied into the repository.

  python3 staging/tools/gbpano.py build <master.png|.jpg|.webp> [--version pano-YYYY-MM-DD]
                                         [--out assets/world] [--tile 1024] [--no-mark]
  python3 staging/tools/gbpano.py check <master>      # size + seam report only, writes nothing
  python3 staging/tools/gbpano.py clear               # back to fallback mode (manifest = null)

What build does
  * reads the master's real size (nothing is hard-coded; any width/height works)
  * reports the wrap seam (left vs right edge difference) — a 360° loop must match there
  * tiers: low 540 px, medium 1080 px, high 2160 px tall (capped at the master's height;
    duplicates dropped). Each tier is cut into vertical strips (--tile px wide, last strip
    narrower) so a phone never downloads the whole loop
  * overview: the whole loop at 2048 px wide (first paint + minimap)
  * every file carries the gbmedia rights metadata (XMP/IPTC/EXIF, exact notice);
    with marking on (default) a faint notice is drawn into the bottom edge of every 4th tile
  * writes panorama-manifest.js (window.GB_PANORAMA) — then run tools/revision.py,
    which stamps the tile revisions and checks every tile exists

After building: measure region positions on the master, fill world-data.js `world` values,
set GB_WORLD.coordinateAuthority to the version printed here, test, publish.
"""
import datetime, json, os, re, shutil, sys
from PIL import Image, ImageDraw, ImageFont

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)
import gbmedia  # noqa: E402  (same folder: shared notice, metadata and save())

STAGING = os.path.dirname(HERE)
MANIFEST = os.path.join(STAGING, "panorama-manifest.js")
TIER_HEIGHTS = (("low", 540), ("medium", 1080), ("high", 2160))
OVERVIEW_W = 2048
Image.MAX_IMAGE_PIXELS = None          # masters are large on purpose (e.g. 14 400 px wide)

HEADER = """// GB GAMER BROS™ — Adventure Mountain™ 360° panorama manifest.
// Generated by tools/gbpano.py; revisions stamped by tools/revision.py. Do not edit by hand.
//
// null = no panorama installed: the world viewer runs in FALLBACK mode (current front map).
// When gbpano.py writes an object here the viewer switches to PANORAMA mode automatically.
//
// Contract (all paths relative to /staging/; w/h in px; `rev` = content revision):
// window.GB_PANORAMA = {
//   version:   "pano-YYYY-MM-DD[-n]",          // panorama version label (coordinate authority)
//   width, height,                              // master size, read from the source at build time
//   copyright: "2026 Copyright © …",
//   overview:  { src, w, h, rev },               // whole loop, small: first paint + minimap
//   tiers: [                                     // ascending height; the viewer picks per screen
//     { name: "low"|"medium"|"high", height, width,
//       tiles: [ { src, w, rev }, … ] }          // left→right vertical strips covering 0…width
//   ]
// };
"""


def write_manifest(obj):
    body = "null" if obj is None else json.dumps(obj, indent=1, ensure_ascii=False)
    open(MANIFEST, "w", encoding="utf-8").write(HEADER + f"window.GB_PANORAMA = {body};\n")


def seam(im):
    """Mean absolute RGB difference between the first and last pixel columns (0–255)."""
    h = min(im.height, 2048)
    small = im.convert("RGB").resize((im.width * h // im.height or 1, h)) if im.height > h else im.convert("RGB")
    a = small.crop((0, 0, 1, small.height)).tobytes()
    b = small.crop((small.width - 1, 0, small.width, small.height)).tobytes()
    return sum(abs(x - y) for x, y in zip(a, b)) / len(a)


def mark(tile):
    """Faint ownership line along the bottom edge (subtle; not a watermark over the art)."""
    w, h = tile.size
    size = max(9, h // 90)
    font = ImageFont.truetype(gbmedia.FONT, size)
    layer = Image.new("RGBA", tile.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    tw = d.textlength(gbmedia.NOTICE, font=font)
    if tw < w * 0.95:
        d.text((w - tw - size, h - size * 0.6), gbmedia.NOTICE, font=font, anchor="ls", fill=(255, 255, 255, 46))
    return Image.alpha_composite(tile.convert("RGBA"), layer).convert("RGB")


def check(master):
    im = Image.open(master)
    s = seam(im)
    print(f"master {master}: {im.width} x {im.height} px, aspect {im.width / im.height:.3f}:1")
    print(f"wrap seam (edge column difference): {s:.1f} / 255 "
          f"{'— OK' if s < 12 else '— CHECK: left and right edges may not loop seamlessly'}")
    return im


def build(master, version, out_rel, tile_w, marking):
    im = check(master).convert("RGB")
    W, H = im.size
    out = os.path.join(STAGING, out_rel)
    if os.path.isdir(out):
        shutil.rmtree(out)                 # old tiers/tiles must not linger as orphans
    os.makedirs(out)
    tiers, seen = [], set()
    for name, th in TIER_HEIGHTS:
        th = min(th, H)
        if th in seen:
            continue
        seen.add(th)
        tw = round(W * th / H)
        scaled = im.resize((tw, th), Image.LANCZOS)
        tiles, x, n = [], 0, 0
        while x < tw:
            w = min(tile_w, tw - x)
            t = scaled.crop((x, 0, x + w, th))
            if marking and n % 4 == 2:
                t = mark(t)
            rel = f"{out_rel}/{name}-{n:02d}.webp"
            gbmedia.save(t, os.path.join(STAGING, rel), quality=82 if th > 1200 else 84)
            tiles.append({"src": rel, "w": w})
            x += w
            n += 1
        tiers.append({"name": name, "height": th, "width": tw, "tiles": tiles})
        print(f"tier {name}: {tw} x {th}, {len(tiles)} tiles")
    ow = min(OVERVIEW_W, W)
    oh = round(H * ow / W)
    ov_rel = f"{out_rel}/overview.webp"
    gbmedia.save(im.resize((ow, oh), Image.LANCZOS), os.path.join(STAGING, ov_rel), quality=80)
    write_manifest({
        "version": version, "width": W, "height": H, "copyright": gbmedia.NOTICE,
        "overview": {"src": ov_rel, "w": ow, "h": oh},
        "tiers": tiers,
    })
    print(f"wrote panorama-manifest.js ({version}). Next: tools/revision.py, then lock world-data.js coordinates.")


if __name__ == "__main__":
    args = sys.argv[1:]
    if not args:
        raise SystemExit(__doc__)
    if args[0] == "clear":
        write_manifest(None)
        print("panorama-manifest.js reset: fallback mode")
    elif args[0] == "check" and len(args) == 2:
        check(args[1])
    elif args[0] == "build" and len(args) >= 2:
        opt = lambda k, d: args[args.index(k) + 1] if k in args else d   # noqa: E731
        version = opt("--version", "pano-" + datetime.date.today().isoformat())
        if not re.fullmatch(r"pano-[0-9A-Za-z.-]+", version):
            raise SystemExit("--version must look like pano-YYYY-MM-DD")
        build(args[1], version, opt("--out", "assets/world").strip("/"), int(opt("--tile", "1024")), "--no-mark" not in args)
    else:
        raise SystemExit(__doc__)
