#!/usr/bin/env python3
"""GB GAMER BROS™ — staging revision stamping and checks.

Run from anywhere:  python3 staging/tools/revision.py
                    python3 staging/tools/revision.py --check   (verify only, no writes)

What it does
  * gives every public file a content revision (first 10 hex of SHA-1):
      - index.html src/href to local files   ->  file?v=<rev>
      - staging.css url(...) to local files   ->  url(file?v=<rev>)
      - media-manifest.js entries             ->  "rev" (full) and "srev" (-960) per image
        (staging.js builds every image URL from these)
  * computes a build revision from all public files and writes it to
      revision.json, <meta name="gb-revision">, the inline freshness check and the footer
  * checks: every referenced file exists, no unrevisioned local reference remains,
    and lists public asset files nothing references (obsolete leftovers)

A changed file gets a new URL, so browsers and the CDN cannot serve the old copy;
unchanged files keep their URL and stay cached. The HTML itself is re-checked on load
against revision.json (fetched with cache: no-store) and reloads once if a newer build exists.
"""
import hashlib, json, os, re, sys

STAGING = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PRIVATE = (".md",)                     # never published
PRIVATE_DIRS = ("tools",)


def h(path, n=10):
    return hashlib.sha1(open(path, "rb").read()).hexdigest()[:n]


def rel(p):
    return os.path.relpath(p, STAGING).replace(os.sep, "/")


def public_files():
    out = []
    for root, dirs, files in os.walk(STAGING):
        dirs[:] = [d for d in dirs if rel(os.path.join(root, d)) not in PRIVATE_DIRS and not d.startswith(".")]
        for f in files:
            p = os.path.join(root, f)
            if f.endswith(PRIVATE) or f.startswith("."):
                continue
            out.append(rel(p))
    return sorted(out)


LOCAL = r"(?:assets/[^\"'?)\s]+|[A-Za-z0-9_.-]+\.(?:css|js|json))"


def stamp_refs(text, pattern):
    def sub(m):
        path = m.group("path")
        full = os.path.join(STAGING, path)
        if not os.path.isfile(full):
            raise SystemExit(f"missing referenced file: {path}")
        return m.group("pre") + path + "?v=" + h(full) + m.group("post")
    return re.sub(pattern, sub, text)


def load_manifest():
    t = open(os.path.join(STAGING, "media-manifest.js"), encoding="utf-8").read()
    return json.loads(t[t.index("{"): t.rindex("}") + 1])


def write_manifest(m):
    body = json.dumps(dict(sorted(m.items())), indent=1, ensure_ascii=False)
    open(os.path.join(STAGING, "media-manifest.js"), "w", encoding="utf-8").write(
        "// Generated by tools/gbmedia.py and tools/revision.py — do not edit by hand.\n"
        "// w/h = content image (what layouts and hotspots use); band = copyright overscan below it;\n"
        "// rev/srev = content revision of the full and -960 files (cache busting).\n"
        f"window.GB_MEDIA = {body};\n")


FRESH = """<script id="gbFresh">/* reload once if a newer staging build exists (HTML may be cached up to ~10 min) */
(function(){var R="{REV}";try{fetch("revision.json?t="+Date.now(),{cache:"no-store"}).then(function(r){return r.ok?r.json():null}).then(function(j){if(!j||!j.revision||j.revision===R)return;var k="gb-rev-reload",d=null;try{d=sessionStorage.getItem(k)}catch(e){}if(d===j.revision)return;try{sessionStorage.setItem(k,j.revision)}catch(e){}var u=new URL(location.href);u.searchParams.set("r",j.revision);location.replace(u.toString())}).catch(function(){})}catch(e){}})();
</script>"""


def run(check_only=False):
    # 1. image revisions in the manifest
    m = load_manifest()
    for key, e in m.items():
        e["rev"] = h(os.path.join(STAGING, key + ".webp"))
        e["srev"] = h(os.path.join(STAGING, key + "-960.webp"))
    if not check_only:
        write_manifest(m)

    # 2. CSS url(...) references
    css_p = os.path.join(STAGING, "staging.css")
    css = open(css_p, encoding="utf-8").read()
    css2 = stamp_refs(css, r"(?P<pre>url\()(?P<path>" + LOCAL + r")(?:\?v=[0-9a-f]+)?(?P<post>\))")
    if not check_only:
        open(css_p, "w", encoding="utf-8").write(css2)

    # 3. build revision from every public file except index.html / revision.json
    files = [f for f in public_files() if f not in ("index.html", "revision.json")]
    digest = hashlib.sha1()
    for f in files:
        digest.update(f.encode() + b"\0" + open(os.path.join(STAGING, f), "rb").read())
    # include the HTML itself, minus the parts that carry the revision
    page = open(os.path.join(STAGING, "index.html"), encoding="utf-8").read()
    page = re.sub(r'<meta name="gb-revision" content="[^"]*">\n?', "", page)
    page = re.sub(r'<script id="gbFresh">.*?</script>\n?', "", page, flags=re.S)
    page = re.sub(r'<span id="gbRev">[^<]*</span>', "", page)
    page = re.sub(r'\?v=[0-9a-f]+', "", page)
    digest.update(b"index.html\0" + page.encode())
    rev = "r-" + digest.hexdigest()[:8]

    # 4. HTML references, revision meta, freshness check, footer label
    html_p = os.path.join(STAGING, "index.html")
    html = open(html_p, encoding="utf-8").read()
    html = stamp_refs(html, r"(?P<pre>(?:src|href)=\")(?P<path>" + LOCAL + r")(?:\?v=[0-9a-f]+)?(?P<post>\")")
    html = stamp_refs(html, r"(?P<pre>url\()(?P<path>" + LOCAL + r")(?:\?v=[0-9a-f]+)?(?P<post>\))")
    # srcset candidates: "path 960w, path 1672w"
    def srcset(m):
        parts = []
        for cand in m.group(1).split(","):
            bits = cand.strip().split()
            path = bits[0].split("?")[0]
            full = os.path.join(STAGING, path)
            if not os.path.isfile(full):
                raise SystemExit(f"missing srcset file: {path}")
            parts.append(" ".join([path + "?v=" + h(full)] + bits[1:]))
        return 'srcset="' + ", ".join(parts) + '"'
    html = re.sub(r'srcset="([^"]+)"', srcset, html)
    html = re.sub(r'<meta name="gb-revision" content="[^"]*">\n?', "", html)
    html = re.sub(r'<script id="gbFresh">.*?</script>\n?', "", html, flags=re.S)
    html = html.replace("<meta charset=\"utf-8\">",
                        f"<meta charset=\"utf-8\">\n<meta name=\"gb-revision\" content=\"{rev}\">\n" + FRESH.replace("{REV}", rev), 1)
    html = re.sub(r'<span id="gbRev">[^<]*</span>', f'<span id="gbRev">{rev}</span>', html)
    if not check_only:
        open(html_p, "w", encoding="utf-8").write(html)
        open(os.path.join(STAGING, "revision.json"), "w").write(json.dumps({"revision": rev}) + "\n")

    # 5. checks
    problems = []
    refs = set(re.findall(r'(?:src|href)="(' + LOCAL + r')(\?v=[0-9a-f]+)?"', html))
    for path, v in refs:
        if not v:
            problems.append(f"unrevisioned reference: {path}")
    for ss in re.findall(r'srcset="([^"]+)"', html):
        for cand in ss.split(","):
            u = cand.strip().split()[0]
            path, _, v = u.partition("?v=")
            if not v:
                problems.append(f"unrevisioned srcset: {path}")
            refs.add((path, "?v=" + v if v else ""))
    for path, v in re.findall(r"url\((" + LOCAL + r")(\?v=[0-9a-f]+)?\)", html + css2):
        if not v:
            problems.append(f"unrevisioned url(): {path}")
        refs.add((path, v))
    referenced = {p for p, _ in refs}
    referenced |= set(re.findall(r"url\((" + LOCAL + r")\?v=", css2))
    for key in m:
        referenced |= {key + ".webp", key + "-960.webp"}
    referenced |= {"revision.json", "index.html"}
    orphans = [f for f in public_files() if f.startswith("assets/") and f not in referenced]
    for f in orphans:
        problems.append(f"unreferenced public asset (obsolete?): {f}")
    print(f"revision {rev}: {len(files) + 1} public files, {len(m)} manifest images")
    for p in problems:
        print("  ! " + p)
    return rev, problems


if __name__ == "__main__":
    rev, problems = run("--check" in sys.argv)
    sys.exit(1 if problems else 0)
